[package]
name = "file-locker"
version = "0.1.1"
authors = ["Jonathan LEI <xJonathan@outlook.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
rpassword = "5.0.1"
sha2 = "0.9.5"
aes = "0.7.4"
getrandom = "0.2.3"
tempfile = "3.2.0"
block-modes = { version = "0.8.1", features = ["alloc"] }
